# Generated by Django 3.2.5 on 2021-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image_main',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
