# Generated by Django 3.2.5 on 2021-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image_1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_6',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
