# Generated by Django 3.2.5 on 2021-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_clinics'),
        ('clinics', '0003_auto_20210729_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
