# Generated by Django 3.2.5 on 2021-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
        ('clinics', '0004_clinic_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='symptoms_handled',
            field=models.ManyToManyField(to='symptoms.Symptom'),
        ),
    ]
