# Generated by Django 3.2.5 on 2021-07-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
